config/routes.rb
Rails.application.routes.draw do

  get 'programs', to: 'programs#search'
  
  resources :recordings
  resources :recordeds, only: [:index, :show, :destroy]
  get "recordeds/download/:id", to: 'recordeds#download'
  root 'static_pages#index'
  resources :areas, only: [:index, :show]
  resources :stations, only: [:index, :show]
  resource :configure, only: [:edit, :update]
  get :config, to: 'configures#edit'
  put :config, to: 'configures#update'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  

end

app/models/station.rb
class Station < ApplicationRecord
  
  def to_param
    "#{station_id}"
  end
end

app/controllers/stations_controller.rb
# coding: utf-8
class StationsController < ApplicationController
  before_action :set_item, only: [:show]
  
  def index
    @stations = Station.all
  end

  def show
    
  end
  
  
  
  private

  def set_item
    @today = Date.today.in_time_zone
    monday = @today.beginning_of_week
    @week = Array.new(7);
    for i in 0..6 do
      @week[i] = (monday + i.day)
    end
    
    @station = Station.find_by_station_id(params[:id])
    @station_id = @station.station_id
    @area_id = @station.area_id
    @station_name = @station.station_name
    @programs = Program.where(station_id: @station_id).where("start_date >= ?", @week[0]).order("start_date")
    @firstProgram_ids_ofDay = Array.new(7)
    for i in 0..6 do
      if @programs.find_by("start_date >= ? and start_date < ?", @week[i], (@week[i]+1.day)) != nil
      then
        @firstProgram_ids_ofDay[i] = @programs.find_by("start_date >= ? and start_date < ?", @week[i], (@week[i]+1.day)).id
      else
        @firstProgram_ids_ofDay[i] = nil;
      end
    end
  end
end

app/helpers/stations_helper.rb
# coding: utf-8
module StationsHelper
  def get_dayofweek_kana_from_date(date)
    case date - date.beginning_of_week
    when 0.day then
      return "月"
    when 1.day then
      return "火"
    when 2.day then
      return "水"
    when 3.day then
      return "木"
    when 4.day then
      return "金"
    when 5.day then
      return "土"
    when 6.day then
      return "日"
    else
      return nil
    end
  end
  
  
  
  def get_dayofweek_eng_from_date(date)
    case date - date.beginning_of_week
    when 0.day then
      return "mon"
    when 1.day then
      return "tue"
    when 2.day then
      return "wed"
    when 3.day then
      return "thu"
    when 4.day then
      return "fri"
    when 5.day then
      return "sut"
    when 6.day then
      return "sun"
    else
      return nil
    end
  end
end

app/views/stations/index.html.erb
<h2>Stations</h2>

<table class="table">
  <thead>
    <tr>
      <th>station_id</th>
      <th>station_name</th>
      <th>area_id</th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
	<td><%= link_to station.station_id, station_path(station) %></td>
	<td><%= station.station_name %></td>
	<td><%= station.area_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stations/show.html.erb
<div class="row">
  <div class="col-lg-2 col-md-2 col-sm-3 hidden-xs">
    <div class="sidebar-nav-fixed">
      <div class="navbar navbar-default text-center">
	
	<div class="navbar-header">
	  <%= link_to @station_name, station_path(@station), class: "navbar-brand" %>
	</div>
	
	<ul class="nav nav-pills nav-stacked">
	  <div class="divider-vertical"></div>
	  <% for i in 0..6 do %>
	    <li><%= link_to "#{@week[i].month}月#{@week[i].day}日(#{get_dayofweek_kana_from_date(@week[i])})", "##{get_dayofweek_eng_from_date(@week[i])}" %></li>
	  <% end %>
	</ul>
      </div>
    </div>
  </div>
  
  <div class="col-lg-10 col-md-10 col-sm-9 col-xs-12">
    <table class="table">
      <thead>
	<tr>
	  <th class="col-sm-1 col-xs-2">start</th>
	  <th class="col-sm-1 col-xs-2">end</th>
	  <th class="col-sm-1 col-xs-2">dur(s)</th>
	  <th class="col-sm-4 col-xs-4">title</th>
	  <th class="col-sm-4 hidden-xs">performers</th>
	  <th class="col-sm-1 col-xs-2"></th>
	</tr>
      </thead>
      
      <tbody>
	<% week = @week.clone %>
	
	<% @programs.each do |program| %>
	  <% if @firstProgram_ids_ofDay.include?(program.id) %>
	    <% date = week.shift %>
	    <tr id="<%= get_dayofweek_eng_from_date(date) %>">
	      <th colspan="5">
		<%= p "#{date.month}月#{date.day}日(#{get_dayofweek_kana_from_date(date)})" %>
	      </th>
	    </tr>
	  <% end %>
	  <tr id=<%= program.id %>>
	    <td class="col-xs-2"><%= program.start_date.strftime('%H:%M') %></td>
	    <td class="col-xs-2"><%= program.end_date.strftime('%H:%M') %></td>
	    <td class="col-xs-2"><%= program.duration_sec %></td>
	    <td class="col-xs-4"><%= program.title %></td>
	    <td class="hidden-xs"><%= program.performers %></td>
	    <td class="col-xs-2"><%= link_to 'rec', new_recording_path(program_id: program.id) %></td>
	  </tr>
	<% end %>
      </tbody>
    </table>
  </div>