config/routes.rb
Rails.application.routes.draw do

  get 'programs', to: 'programs#search'
  
  resources :recordings
  resources :recordeds, only: [:index, :show, :destroy]
  get "recordeds/download/:id", to: 'recordeds#download'
  root 'static_pages#index'
  resources :areas, only: [:index, :show]
  resources :stations, only: [:index, :show]
  resource :configure, only: [:edit, :update]
  get :config, to: 'configures#edit'
  put :config, to: 'configures#update'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  

end

app/models/recording.rb
class Recording < ApplicationRecord
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: [:show, :edit, :update, :destroy]

  # GET /recordings
  # GET /recordings.json
  def index
    @recordings = Recording.where(is_recorded: false).order(:start_datetime).reverse_order.page(params[:page]).per(20)
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
  end

  # GET /recordings/new
  def new
    if params[:program_id] == nil || !Program.exists?(params[:program_id])
      @recording = Recording.new
    else
      program_params = Hash.new
      program = Program.find(params[:program_id])
      program_params[:station_id] = program.station_id
      program_params[:start_datetime] = program.start_date
      program_params[:recording_second] = program.duration_sec
      program_params[:title] = program.title
      program_params[:filename] = program.start_date.strftime('%Y%m%d%H%M') + "_" +
                                  program.title.gsub(/:|;|>|<|"|\/|\?|\\|\*|\|/,"_") +
                                  ".m4a"
      @recording = Recording.new(program_params)
    end
  end

  # GET /recordings/1/edit
  def edit
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(recording_params)
    @recording.update_attribute(:is_recorded, false)

    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render :show, status: :created, location: @recording }
        job_id = RecordingWorker.perform_at(@recording.start_datetime, @recording.id)
        @recording.update_attribute(:job_id, job_id)
      else
        format.html { render :new }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1
  # PATCH/PUT /recordings/1.json
  def update
    respond_to do |format|
      if @recording.update(recording_params)
        @recording.update_attribute(:is_recorded, false)
        format.html { redirect_to @recording, notice: 'Recording was successfully updated.' }
        format.json { render :show, status: :ok, location: @recording }
        Sidekiq::ScheduledSet.new.select { |retri|
          retri.jid == @recording.job_id
        }.each(&:delete)
        job_id = RecordingWorker.perform_at(@recording.start_datetime, @recording.id)
        @recording.update_attribute(:job_id, job_id)

      else
        format.html { render :edit }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    job_id = @recording.job_id
    @recording.destroy
    respond_to do |format|
      format.html { redirect_to recordings_url, notice: 'Recording was successfully destroyed.' }
      format.json { head :no_content }
    end
    Sidekiq::ScheduledSet.new.select { |retri|
      retri.jid == @recording.job_id
    }.each(&:delete)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recording
      @recording = Recording.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recording_params
      #params.require(:recording).permit(:area_id, :station_id, :start_datetime, :recording_second, :title, :filename, :is_recorded)
      params.require(:recording).permit(:area_id, :station_id, :start_datetime, :recording_second, :title, :filename, :job_id)
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.number_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :station_id %><br>
    <%= f.text_field :station_id %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br>
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :recording_second %><br>
    <%= f.number_field :recording_second %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<h1>Editing Recording</h1>

<%= render 'form' %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Recordings</h2>

<%= paginate @recordings %>

<table class="table">
  <thead>
    <tr>
      <th>station</th>
      <th>start</th>
      <th>dur(s)</th>
      <th>title</th>
      <th>filename</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @recordings.each do |recording| %>
      <tr>
        <td><%= recording.station_id %></td>
	<th><%= recording.start_datetime.strftime("%Y/%m/%d %H:%M") %></th>
        <td><%= recording.recording_second %></td>
        <td><%= recording.title %></td>
        <td><%= recording.filename %></td>
        <td><%= link_to 'edit', edit_recording_path(recording) %></td>
        <td><%= link_to 'destroy', recording, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @recordings %>

<br>

<%= link_to 'New Recording', new_recording_path %>

app/views/recordings/new.html.erb
<h1>New Recording</h1>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @recording.area_id %>
</p>

<p>
  <strong>Station:</strong>
  <%= @recording.station_id %>
</p>

<p>
  <strong>Start datetime:</strong>
  <%= @recording.start_datetime %>
</p>

<p>
  <strong>Recording second:</strong>
  <%= @recording.recording_second %>
</p>

<p>
  <strong>Title:</strong>
  <%= @recording.title %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @recording.filename %>
</p>

<p>
  <strong>Is recorded:</strong>
  <%= @recording.is_recorded %>
</p>

<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>