config/routes.rb
Rails.application.routes.draw do

  get 'programs', to: 'programs#search'
  
  resources :recordings
  resources :recordeds, only: [:index, :show, :destroy]
  get "recordeds/download/:id", to: 'recordeds#download'
  root 'static_pages#index'
  resources :areas, only: [:index, :show]
  resources :stations, only: [:index, :show]
  resource :configure, only: [:edit, :update]
  get :config, to: 'configures#edit'
  put :config, to: 'configures#update'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  

end

app/models/area.rb
class Area < ApplicationRecord
  self.primary_key = "area_id"
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_item, only: [:show]
  
  def index
    @areas = Area.all
  end
  
  def show
    monday = Date.today.in_time_zone.beginning_of_week
    @programs = Hash.new
    @stations.each do |station|
      station_id = station.station_id
      @programs[station_id] =
        Program.where(station_id: station_id).where("start_date >= ?", monday).order("start_date")
    end
  end
  
  
  
  private
  
  def set_item
    @area_id = Area.find(params[:id]).area_id
    @area_name_kana = Area.find(params[:id]).area_name_kana
    @stations = Station.where(area_id: params[:id])
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/index.html.erb
<h2>Areas</h2>

<table class="table">
  <thead>
    <tr>
      <th>area_id</th>
      <th>area_name</th>
      <th>area_name_kana</th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
	<td><%= link_to area.area_id, area_path(area) %></td>
	<td><%= area.area_name %></td>
	<td><%= area.area_name_kana %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/areas/show.html.erb
<h2><%= @area_name_kana %></h2>

<div class="multiple-items">
  <% @programs.each do |area_id, programs_each_area| %>
    <div>
      <%= area_id.to_s %>
      <% programs_each_area.each do |program| %>
	<%= content_tag(:div, {class: 'normal-box', style: "height: #{program.duration_sec/20}px"}) do %>
	  <%= link_to program.title, new_recording_path(program_id: program.id) %><br>
	  start: <%= program.start_date.strftime("%H:%M") %><br>
	  end: <%= program.end_date.strftime("%H:%M") %><br>
	  dulation: <%= program.duration_sec %><br>
	  height: <%= program.duration_sec/20 %>
	<% end %>
      <% end %>
    </div>
  <% end %>
</div>