config/routes.rb
Rails.application.routes.draw do

  get 'programs', to: 'programs#search'
  
  resources :recordings
  resources :recordeds, only: [:index, :show, :destroy]
  get "recordeds/download/:id", to: 'recordeds#download'
  root 'static_pages#index'
  resources :areas, only: [:index, :show]
  resources :stations, only: [:index, :show]
  resource :configure, only: [:edit, :update]
  get :config, to: 'configures#edit'
  put :config, to: 'configures#update'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  self.primary_key = "area_id"
end

app/models/configure.rb
class Configure < ApplicationRecord
  validates :key, uniqueness: true
end

app/models/program.rb
class Program < ApplicationRecord
  
  # searching method
  def self.search(search_word = nil)
    unless search_word.blank?
      where("title like ? or subtitle like ? or performers like ?",
           "%" + search_word + "%",
           "%" + search_word + "%",
           "%" + search_word + "%")
    else
      nil
    end
  end
end

app/models/recording.rb
class Recording < ApplicationRecord
end

app/models/station.rb
class Station < ApplicationRecord
  
  def to_param
    "#{station_id}"
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_item, only: [:show]
  
  def index
    @areas = Area.all
  end
  
  def show
    monday = Date.today.in_time_zone.beginning_of_week
    @programs = Hash.new
    @stations.each do |station|
      station_id = station.station_id
      @programs[station_id] =
        Program.where(station_id: station_id).where("start_date >= ?", monday).order("start_date")
    end
  end
  
  
  
  private
  
  def set_item
    @area_id = Area.find(params[:id]).area_id
    @area_name_kana = Area.find(params[:id]).area_name_kana
    @stations = Station.where(area_id: params[:id])
  end
end

app/controllers/configures_controller.rb
class ConfiguresController < ApplicationController

  def edit
    @path_ffmpeg = Configure.find_or_create_by(key: "path_ffmpeg").value
    @path_mp4box = Configure.find_or_create_by(key: "path_mp4box").value
    @storedir = Configure.find_or_create_by(key: "storedir").value
  end



  def update
    if params[:commit] == "change"

      # update path_ffmpeg
      path_ffmpeg_record = Configure.find_or_create_by(key: "path_ffmpeg")
      path_ffmpeg_record.update_attributes(value: params[:path_ffmpeg])

      # update path_mp4box
      path_mp4box_record = Configure.find_or_create_by(key: "path_mp4box")
      path_mp4box_record.update_attributes(value: params[:path_mp4box])

      # update storedir
      storedir_record = Configure.find_or_create_by(key: "storedir")
      if params[:storedir].empty?
        @error = "Empty storedir is not allowed."
      else
        if storedir_record.update_attributes(value: params[:storedir])
          @success = "Configure updated."
        else
          @error = "Failed to update configure."
        end
      end

      # re-render
      @path_ffmpeg = Configure.find_or_create_by(key: "path_ffmpeg").value
      @path_mp4box = Configure.find_or_create_by(key: "path_mp4box").value
      @storedir = Configure.find_or_create_by(key: "storedir").value
      render :edit

    elsif params[:commit] == "cancel"
      @storedir = Configure.find_or_create_by(key: "storedir").value
      render :edit
    end
  end
end

app/controllers/program_controller.rb
class ProgramController < ApplicationController
  def index
    @programs = Program.search(params[:search_word])
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:search_word)
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def search
    @programs = Program.search(params[:search_word])
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:search_word)
  end
end

app/controllers/recordeds_controller.rb
class RecordedsController < ApplicationController
  before_action :set_recording, only: [:show, :destroy, :download]

  # GET /recorded
  def index
    @recordings = Recording.where(is_recorded: true).order(:start_datetime).reverse_order.page(params[:page]).per(20)
  end

  def show
  end

  # DELETE /recorded/1
  def destroy
    @recording.destroy
    storedir = "/var/radikko"
    if Configure.exists?(key: 'storedir') &&
         !Configure.find_by(key: 'storedir').value.blank?
      storedir = Configure.find_by(key: 'storedir').value
    end
    
    file_path = storedir + "/" + @recording.filename
    if File.exist?(file_path)
      File.delete(file_path)
    end
    redirect_to recordeds_url, notice: 'Recorded was successfully destroyed.'
  end

  def download
    storedir = "/var/radikko"
    if Configure.exists?(key: 'storedir') &&
         !Configure.find_by(key: 'storedir').value.blank?
      storedir = Configure.find_by(key: 'storedir').value
    end

    file_path = storedir + "/" + @recording.filename
    send_file(file_path, filename: @recording.filename)
  end

  private
  def set_recording
    @recording = Recording.find(params[:id])
  end

end

app/controllers/stations_controller.rb
# coding: utf-8
class StationsController < ApplicationController
  before_action :set_item, only: [:show]
  
  def index
    @stations = Station.all
  end

  def show
    
  end
  
  
  
  private

  def set_item
    @today = Date.today.in_time_zone
    monday = @today.beginning_of_week
    @week = Array.new(7);
    for i in 0..6 do
      @week[i] = (monday + i.day)
    end
    
    @station = Station.find_by_station_id(params[:id])
    @station_id = @station.station_id
    @area_id = @station.area_id
    @station_name = @station.station_name
    @programs = Program.where(station_id: @station_id).where("start_date >= ?", @week[0]).order("start_date")
    @firstProgram_ids_ofDay = Array.new(7)
    for i in 0..6 do
      if @programs.find_by("start_date >= ? and start_date < ?", @week[i], (@week[i]+1.day)) != nil
      then
        @firstProgram_ids_ofDay[i] = @programs.find_by("start_date >= ? and start_date < ?", @week[i], (@week[i]+1.day)).id
      else
        @firstProgram_ids_ofDay[i] = nil;
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/configures_helper.rb
module ConfiguresHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/recordeds_helper.rb
module RecordedsHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stations_helper.rb
# coding: utf-8
module StationsHelper
  def get_dayofweek_kana_from_date(date)
    case date - date.beginning_of_week
    when 0.day then
      return "月"
    when 1.day then
      return "火"
    when 2.day then
      return "水"
    when 3.day then
      return "木"
    when 4.day then
      return "金"
    when 5.day then
      return "土"
    when 6.day then
      return "日"
    else
      return nil
    end
  end
  
  
  
  def get_dayofweek_eng_from_date(date)
    case date - date.beginning_of_week
    when 0.day then
      return "mon"
    when 1.day then
      return "tue"
    when 2.day then
      return "wed"
    when 3.day then
      return "thu"
    when 4.day then
      return "fri"
    when 5.day then
      return "sut"
    when 6.day then
      return "sun"
    else
      return nil
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
    <p class="text-right text-nowrap" style="padding-right:36px">
      <span class="glyphicon glyphicon-copyright-mark"></span>
      uehashu, 2015-2019
    </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
		data-target="#header-cllapsed" aria-expanded="false">
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	</button>
	<%= link_to :Radikko, root_path, class: "navbar-brand" %>
      </div>
      
      <div class="collapse navbar-collapse" id="header-cllapsed">
	<ul class="nav navbar-nav">
	  <li><%= link_to :Area, areas_path %></li>
	  <li><%= link_to :Station, stations_path %></li>
	  <li><%= link_to :Recording, recordings_path %></li>
	  <li><%= link_to :Recorded, recordeds_path %></li>
	  <li class="hidden-xs"><%= link_to config_path do %>
	    <span class="glyphicon glyphicon-cog"></span>
	  <% end %>
	  </li>
	  <li class="visible-xs"><%= link_to :Config, config_path %></li>
	</ul>
	
	<%= form_tag programs_path, method: "get", enforce_utf8: false, class: "navbar-form navbar-left", role: "search" do %>
	  <div class="input-group">
	    <%= text_field_tag 'search_word', nil , placeholder: "Search", class: "form-control" %>
	    <span class="input-group-btn">
	      <%= button_to "", method: "get", type: "submit", class: "btn btn-default" do %>
		<span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
          </div>
	<% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <script>
    var shiftWindow = function() { scrollBy(0, -50) };
    window.addEventListener("hashchange", shiftWindow);
    function load() { if (window.location.hash) shiftWindow(); }
    </script>
    
    <title>Radikko</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    <%= render "layouts/shim" %>
  </head>
  
  <body onload="load()">
    <%= render "layouts/header" %>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <%= render "layouts/footer" %>
  </body>
  
</html>